### ISSUE TITLE
Bad CRC

### ISSUE THREAD

**Issue by mjibson** [mccoyst/ogg#5]
I have just encoded a wav file to ogg using oggenc version 1.4.0. This package reports a bad CRC when reading that file. Same results with various other .ogg files I have downloaded from the Internet. I've been looking at the spec and the code and can't see anything obviously wrong.

**Comment by mccoyst** [comment]
Hmm, I'll check it out tonight. Thanks!

**Comment by mccoyst** [comment]
I still have to try to reproduce your scenario, but in the meantime, updating to c024df72cfb should at least give a more informative error message.

**Comment by mccoyst** [comment]
Ugh, the entries in the `crcTable` differ from the table in [libogg](https://git.xiph.org/?p=ogg.git;a=blob;f=src/framing.c;h=506cf8aa97eeb622d96f571d60a995b0a20f5912;hb=refs/heads/master). It's not clear to me who's really wrong, but I don't have much choice here. I'll just copy their table instead of using `crc32.MakeTable()` and see how it goes.

**Comment by mccoyst** [comment]
Still doesn't work. Turns out `crc32` does reflected CRC and ogg wants unreflected.
